### ISSUE TITLE
createPlaylist method

### ISSUE THREAD

**Issue by MugiwaraSama** [meronbrouwer/oose-dea-eai-client#6]
I have a question regarding the createPlaylist method;

Why does the createPlaylist method have to return a list of updated playlists(for example a method called getAllPlaylists)? Isn't the purpose of this method to only create a new playlist? After a successfully created playlist the client should return a refreshed page.

**Comment by meronbrouwer** [comment]
Currently all requests will expect a response that contains all data required to display the new state of the system. This is more from a pragmatic point-of-view, than from an ideal point-of-view. 

So, I guess you are correct. But since this is an exercise/assignment, we choose a different approach.

**Comment by MugiwaraSama** [comment]
Oke, then it makes sense.
